# Generated by Django 3.1.4 on 2020-12-31 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNursery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.TextField()),
                ('shopAddress', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NurseryCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery.mynursery')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plant.plant')),
            ],
        ),
    ]
