# Generated by Django 3.1.4 on 2020-12-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.TextField(choices=[('tree', 'Tree'), ('shrub', 'Shrub'), ('herb', 'Herb'), ('climber', 'Climber'), ('creeper', 'Creeper')], default='Tree')),
                ('about', models.TextField(null=True)),
                ('cost', models.FloatField()),
                ('image', models.ImageField(default='default.jpg', upload_to='plantPic')),
            ],
        ),
    ]
