# Generated by Django 3.1.4 on 2020-12-31 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nursery', '0001_initial'),
        ('Plant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTocart_on', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plant.plant')),
                ('shopFrom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Nursery.mynursery')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('customer', 'Customer'), ('seller', 'Seller')])),
                ('phone', models.BigIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedAt', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customercart')),
                ('shopFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery.mynursery')),
            ],
        ),
    ]
