# Generated by Django 3.1.4 on 2020-12-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='shopFrom',
        ),
    ]
