# Generated by Django 3.1.4 on 2020-12-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_placeorder_shopfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='shopId',
            field=models.IntegerField(default=0),
        ),
    ]
